[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gapin-sdk-python"
version = "1.0.0"
description = "Python SDK for Gapin"
dependencies = [
    "requests==2.32.3",
    "blake3==0.4.1",
    # Optional later:
    # "pydantic==2.6.4",
    # "onnxruntime==1.17.1"
]

[tool.setuptools.packages.find]
where = ["src"]